seed: 42

data_dir: './data'
snr: '0_dB'

train_dirs:
  - '../STgram-MFN/data/dataset/fan/train'
  - '../STgram-MFN/data/dataset/pump/train'
  - '../STgram-MFN/data/dataset/slider/train'
  - '../STgram-MFN/data/dataset/valve/train'

add_dirs:
  - '../STgram-MFN/data/eval_dataset/fan/train'
  - '../STgram-MFN/data/eval_dataset/pump/train'
  - '../STgram-MFN/data/eval_dataset/slider/train'
  - '../STgram-MFN/data/eval_dataset/valve/train'

val_dirs:
  - '../STgram-MFN/data/dataset/fan/test'
  - '../STgram-MFN/data/dataset/pump/test'
  - '../STgram-MFN/data/dataset/slider/test'
  - '../STgram-MFN/data/dataset/valve/test'

test_dirs:
  - '../STgram-MFN/data/eval_dataset/fan/test'
  - '../STgram-MFN/data/eval_dataset/pump/test'
  - '../STgram-MFN/data/eval_dataset/slider/test'
  - '../STgram-MFN/data/eval_dataset/valve/test'

batch_size: 64

epoch: 100
valid_interval: 10
load_epoch: 'best'