seed: 42

data_dir: './data'
snr: '-6_dB'

train_dirs:
  - './data/-6_dB/fan/train'
  - './data/-6_dB/pump/train'
  - './data/-6_dB/slider/train'
  - './data/-6_dB/valve/train'

# add_dirs:
#   - './data/-6_dB/test/fan/train'
#   - './data/-6_dB/test/pump/train'
#   - './data/-6_dB/test/slider/train'
#   - './data/-6_dB/test/valve/train'

val_dirs:
  - './data/-6_dB/fan/val'
  - './data/-6_dB/pump/val'
  - './data/-6_dB/slider/val'
  - './data/-6_dB/valve/val'

test_dirs:
  - './data/-6_dB/fan/test'
  - './data/-6_dB/pump/test'
  - './data/-6_dB/slider/test'
  - './data/-6_dB/valve/test'

batch_size: 64

epoch: 100
valid_interval: 10
load_epoch: 'best'