train_dir: './track2_dataset/train'
eval_dir: './track2_dataset/eval'
test_dir: './track2_dataset/test'

model_root: './model_track2'

tsne_root: './latent_figs/track2'

result_root: './result'

seed: 42

sample_size: 4096
overlap: 2048

batch_size: 128
learning_rate: 0.001
epoch: 500