train_dir: './dataset/train'
eval_dir: './dataset/eval'
test_dir: './dataset/test'

model_root: './model'

tsne_root: './latent_figs'

result_root: './result'

seed: 42

sample_size: 4096
overlap: 2048

batch_size: 128
learning_rate: 0.001
epoch: 1